### PR TITLE
Dev/mat migration

### PR DESCRIPTION
**Pull request by jmbrnrd**
- packages updated via npm update
- Replaced all deprecated md components
- Update to all component, directives and css md prefixes
- Merged latest KS commits

### CODE REVIEW

**Comment by KenStratford** [comment]
Hi Jim,

That all looks very official. Good stuff.

I have just played with the release (nice to be able to access it from there), and I do notice that for some reason text spacing has changed? Appears to be in several places?

Have a look at, for example, the main curation table.

Also I notice that in the restaurant detail form under curation.

Is this an effect from the MAT changes?

Should probably chat so I understand what is going on! Perhaps a little later today?

Cheers,

Ken

**Comment by KenStratford** [comment]
Hi Jim,

Update on last night’s message

PR-14 has the time input bug!

Very weird - my local version does not. The current production version (for me) does not - but does for Simon. But PR-14 does have it (for me).

Can you try?

Go to Acanthus in Oxfordshire, then see what happens when you update any of time fields.

Hmmmm. My Chrome is V62.

Ken

**Comment by jmbrnrd** [comment]
Just tried editing times for Acanthus on pr-14 without any issues. *Strange*?

**Comment by KenStratford** [comment]
You got a minute so we can try this?

**Comment by KenStratford** [comment]
Aha!

I lied.

PR-14 is OK for me on Chrome, but NOT on Safari.

Sorry, clicked default and assumed I was in Chrome…

So it looks like Safari and older Chrome does not like this?

Odd..

K

**Comment by jmbrnrd** [comment]
Still wanna chat?

**Comment by KenStratford** [comment]
Hi Jim,

Managed to replicate in my local Safari.

Seem to have fixed it. In curation-detail.html L378

           
           
<td><input type="text" size="50" width="70%" align="center"
           [(ngModel)]="day.hours"
           (change)="setTimeChanged()"></td>
Seems it does not like the value being set like that - doing a bit of reading it may about nested calls. Dunno. Quite why it is browser specific also dunno.

My ‘bad’ as you might say. Indeed, the align center is also redundant...

Can you update your version?

Ta, chat later.

Ken

**Pull request merged**
